# Generated by Django 3.2.9 on 2021-11-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211116_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='rules',
            field=models.TextField(blank=True, verbose_name='Пользовательские правила'),
        ),
        migrations.AlterField(
            model_name='memberlist',
            name='place',
            field=models.PositiveSmallIntegerField(verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
